apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush                     1
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 10M
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               gold*
        Path              /var/log/containers/*_namespace1_*.log
        Parser            docker
        DB                /var/log/flb_namespace1.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
    [INPUT]
        Name              tail
        Tag               amber*
        Path              /var/log/containers/*_namespace2_*.log
        Parser            docker
        DB                /var/log/flb_namespace2.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
    [INPUT]
        Name              tail
        Tag               black*
        Path              /var/log/containers/*_namespace3_*.log
        Parser            docker
        DB                /var/log/flb_namespace3.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
    [INPUT]
        Name              tail
        Tag               opal*
        Path              /var/log/containers/*_namespace4_*.log
        Parser            docker
        DB                /var/log/flb_namespace4.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
    [INPUT]
        Name              tail
        Tag               nginx*
        Path              /var/log/containers/*nginx*.log
        Parser            nginx
        DB                /var/log/flb_nginx.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
    [INPUT]
        Name              tail
        Tag               kube-system*
        Path              /var/log/containers/*kube-system*.log
        Parser            docker
        DB                /var/log/flb_kubesystem.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type      filesystem
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               namespace1*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     namespace1.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                kubernetes
        Match               namespace2*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     namespace2.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                kubernetes
        Match               namespace3*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     namespace3.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                kubernetes
        Match               namespace4*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     namespace4.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                kubernetes
        Match               nginx*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     nginx.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name                kubernetes
        Match               kube-system*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube-system.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           namespace1*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix namespace1
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
    [OUTPUT]
        Name            es
        Match           namespace2*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix namespace2
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
    [OUTPUT]
        Name            es
        Match           namespace3*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix namespace3
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
    [OUTPUT]
        Name            es
        Match           namespace4*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix namespace4
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
    [OUTPUT]
        Name            es
        Match           nginx*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix nginx
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
    [OUTPUT]
        Name            es
        Match           kube-system*
        Host            ${CLOUD_ELASTICSEARCH_HOST}
        Port            ${CLOUD_ELASTICSEARCH_PORT}
        Cloud_ID        ${CLOUD_ELASTICSEARCH_ID}
        Cloud_Auth      ${CLOUD_ELASTICSEARCH_USER}:${CLOUD_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix kube-system
        Replace_Dots    On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        storage.total_limit_size 10M
  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S