apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-s3
  namespace: logging # change namespace to yours
data:
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY'
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_KEY'
  REGION: 'AWS_REGION'
  BUCKET: 'AWS_S3_BUCKET'
type: Opaque

# Add this secret only if you woult like to use output s3 plugin.