apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging # change namespace to yours
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.8.9
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: CLOUD_ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-configmap
              key: CLOUD_ELASTICSEARCH_HOST
        - name: CLOUD_ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-configmap
              key: CLOUD_ELASTICSEARCH_PORT
        - name: CLOUD_ELASTICSEARCH_ID
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-configmap
              key: CLOUD_ELASTICSEARCH_ID
        - name: CLOUD_ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: CLOUD_ELASTICSEARCH_USER
        - name: CLOUD_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: CLOUD_ELASTICSEARCH_PASSWORD
  # Secret variables section for output s3 plugin.
  #      - name: AWS_ACCESS_KEY_ID
  #        valueFrom:
  #          secretKeyRef:
  #            name: fluent-bit-s3
  #            key: AWS_ACCESS_KEY_ID
  #      - name: AWS_SECRET_ACCESS_KEY
  #        valueFrom:
  #          secretKeyRef:
  #            name: fluent-bit-s3
  #            key: AWS_SECRET_ACCESS_KEY
  #      - name: REGION
  #        valueFrom:
  #          secretKeyRef:
  #            name: fluent-bit-s3
  #            key: REGION
  #      - name: BUCKET
  #        valueFrom:
  #          secretKeyRef:
  #            name: fluent-bit-s3
  #            key: BUCKET
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
