apiVersion: v1
kind: ConfigMap
metadata:
  name: logtrail-config
  namespace: infra-monitoring
data:
  logtrail.json: |
    {
      "version": 2,
      "index_patterns": [
        {
          "es": {
            "default_index": "namespace1-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        },
        {
          "es": {
            "default_index": "namespace2-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        },
        {
          "es": {
            "default_index": "namespace3-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        },
        {
          "es": {
            "default_index": "namespace4-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        },
        {
          "es": {
            "default_index": "nginx-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        },
        {
          "es": {
            "default_index": "kube-system-*"
          },
          "tail_interval_in_seconds": 10,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days": 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "default_search": "",
          "fields": {
            "message_format": "{{{log}}}",
            "mapping": {
                "timestamp": "@timestamp",
                "hostname": "kubernetes.labels.app",
                "program": "kubernetes.pod_name",
                "message": "log"
            }
          },
          "color_mapping": {
            "field": "logLevel",
            "mapping": {
              "error": "#FF0000",
              "warn": "#FFEF96",
              "debug": "#B5E7A0",
              "trace": "#CFE0E8"
            }
          }
        }
      ]
    }
